max_width = 100
tab_spaces = 4
newline_style = "unix"
edition = "2021"
merge_derives = true
use_small_heuristics = "Default"
binop_separator = "Front"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
format_strings = true
imports_layout = "Vertical"
imports_indent = "Block" 